# Generated by Django 4.2.3 on 2023-08-22 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pro_add',
            old_name='description',
            new_name='Project_Description',
        ),
        migrations.RenameField(
            model_name='pro_add',
            old_name='title',
            new_name='Project_Title',
        ),
    ]
