# Generated by Django 4.2.3 on 2023-08-26 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0002_rename_description_pro_add_project_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='task_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('complete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='pro_add',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pro_add',
            name='Project_Description',
            field=models.CharField(max_length=300),
        ),
    ]
