# Generated by Django 4.2.3 on 2023-08-28 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0003_task_add_pro_add_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_add',
            name='open',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_add', to='pro.pro_add'),
        ),
    ]
