# Generated by Django 4.2.3 on 2023-08-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0005_pro_add_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro_add',
            name='date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
