# Generated by Django 4.2.3 on 2023-08-31 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0006_pro_add_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pro_add',
            name='date',
        ),
    ]
