# Generated by Django 4.2.3 on 2023-09-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0007_remove_pro_add_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro_add',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
