# Generated by Django 4.2.3 on 2023-09-01 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0010_pro_add_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pro_add',
            old_name='date',
            new_name='deadline',
        ),
    ]
