# Generated by Django 4.2.3 on 2023-12-19 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0011_rename_date_pro_add_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pro_add',
            name='complete',
        ),
        migrations.AlterField(
            model_name='pro_add',
            name='deadline',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task_add',
            name='open',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_add', to='pro.pro_add'),
        ),
    ]
