# Generated by Django 4.2.3 on 2023-12-20 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0012_remove_pro_add_complete_alter_pro_add_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_add',
            name='open',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_add', to='pro.pro_add'),
        ),
    ]
